# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `omniauth-twitter` gem.
# Please instead update this file by running `bin/tapioca gem omniauth-twitter`.


# source://omniauth-twitter//lib/omniauth-twitter/version.rb#1
module OmniAuth; end

# source://omniauth-twitter//lib/omniauth/strategies/twitter.rb#5
module OmniAuth::Strategies; end

# source://omniauth-twitter//lib/omniauth/strategies/twitter.rb#6
class OmniAuth::Strategies::Twitter < ::OmniAuth::Strategies::OAuth
  # source://omniauth-twitter//lib/omniauth/strategies/twitter.rb#74
  def callback_path; end

  # source://omniauth-twitter//lib/omniauth/strategies/twitter.rb#66
  def callback_url; end

  # source://omniauth-twitter//lib/omniauth/strategies/twitter.rb#64
  def old_callback_url; end

  # source://omniauth-twitter//lib/omniauth/strategies/twitter.rb#40
  def old_request_phase; end

  # source://omniauth-twitter//lib/omniauth/strategies/twitter.rb#34
  def raw_info; end

  # source://omniauth-twitter//lib/omniauth/strategies/twitter.rb#42
  def request_phase; end

  private

  # source://omniauth-twitter//lib/omniauth/strategies/twitter.rb#86
  def image_url; end
end

# source://omniauth-twitter//lib/omniauth-twitter/version.rb#2
module OmniAuth::Twitter; end

# source://omniauth-twitter//lib/omniauth-twitter/version.rb#3
OmniAuth::Twitter::VERSION = T.let(T.unsafe(nil), String)
