# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `omniauth-oauth` gem.
# Please instead update this file by running `bin/tapioca gem omniauth-oauth`.


# source://omniauth-oauth//lib/omniauth-oauth/version.rb#1
module OmniAuth; end

# source://omniauth-oauth//lib/omniauth-oauth/version.rb#2
module OmniAuth::OAuth; end

# source://omniauth-oauth//lib/omniauth-oauth/version.rb#3
OmniAuth::OAuth::VERSION = T.let(T.unsafe(nil), String)

# source://omniauth-oauth//lib/omniauth/strategies/oauth.rb#5
module OmniAuth::Strategies; end

# source://omniauth-oauth//lib/omniauth/strategies/oauth.rb#6
class OmniAuth::Strategies::OAuth
  include ::OmniAuth::Strategy
  extend ::OmniAuth::Strategy::ClassMethods

  # Returns the value of attribute access_token.
  #
  # source://omniauth-oauth//lib/omniauth/strategies/oauth.rb#18
  def access_token; end

  # source://omniauth-oauth//lib/omniauth/strategies/oauth.rb#44
  def callback_phase; end

  # source://omniauth-oauth//lib/omniauth/strategies/oauth.rb#20
  def consumer; end

  # source://omniauth-oauth//lib/omniauth/strategies/oauth.rb#27
  def request_phase; end
end

class OmniAuth::Strategies::Twitter < ::OmniAuth::Strategies::OAuth; end
