// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategorySelectController from "./category_select_controller"
application.register("category-select", CategorySelectController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import CommentController from "./comment_controller"
application.register("comment", CommentController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)
